/**
 * Generated by Supabase MCP — do not edit manually.
 * Regenerate: npm run db:types
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      contacts: {
        Row: {
          address: string | null
          created_at: string
          created_by: string
          email: string | null
          first_name: string | null
          id: string
          last_name: string | null
          lat: number | null
          lng: number | null
          phone: string | null
          postcode: string | null
          suburb: string | null
        }
        Insert: {
          address?: string | null
          created_at?: string
          created_by: string
          email?: string | null
          first_name?: string | null
          id?: string
          last_name?: string | null
          lat?: number | null
          lng?: number | null
          phone?: string | null
          postcode?: string | null
          suburb?: string | null
        }
        Update: {
          address?: string | null
          created_at?: string
          created_by?: string
          email?: string | null
          first_name?: string | null
          id?: string
          last_name?: string | null
          lat?: number | null
          lng?: number | null
          phone?: string | null
          postcode?: string | null
          suburb?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "contacts_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      door_knocks: {
        Row: {
          contact_id: string
          follow_up_at: string | null
          id: string
          idempotency_key: string | null
          knocked_at: string
          lat: number
          lng: number
          notes: string | null
          outcome: Database["public"]["Enums"]["door_outcome"]
          rep_id: string
          synced: boolean
        }
        Insert: {
          contact_id: string
          follow_up_at?: string | null
          id?: string
          idempotency_key?: string | null
          knocked_at?: string
          lat: number
          lng: number
          notes?: string | null
          outcome: Database["public"]["Enums"]["door_outcome"]
          rep_id: string
          synced?: boolean
        }
        Update: {
          contact_id?: string
          follow_up_at?: string | null
          id?: string
          idempotency_key?: string | null
          knocked_at?: string
          lat?: number
          lng?: number
          notes?: string | null
          outcome?: Database["public"]["Enums"]["door_outcome"]
          rep_id?: string
          synced?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "door_knocks_contact_id_fkey"
            columns: ["contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "door_knocks_rep_id_fkey"
            columns: ["rep_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      follow_ups: {
        Row: {
          completed: boolean
          created_at: string
          due_at: string
          id: string
          lead_id: string
          note: string
          reminded_at: string | null
          rep_id: string
        }
        Insert: {
          completed?: boolean
          created_at?: string
          due_at: string
          id?: string
          lead_id: string
          note?: string
          reminded_at?: string | null
          rep_id: string
        }
        Update: {
          completed?: boolean
          created_at?: string
          due_at?: string
          id?: string
          lead_id?: string
          note?: string
          reminded_at?: string | null
          rep_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "follow_ups_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "follow_ups_rep_id_fkey"
            columns: ["rep_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      gps_pings: {
        Row: {
          id: string
          lat: number
          lng: number
          recorded_at: string
          rep_id: string
          shift_id: string
        }
        Insert: {
          id?: string
          lat: number
          lng: number
          recorded_at?: string
          rep_id: string
          shift_id: string
        }
        Update: {
          id?: string
          lat?: number
          lng?: number
          recorded_at?: string
          rep_id?: string
          shift_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "gps_pings_rep_id_fkey"
            columns: ["rep_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "gps_pings_shift_id_fkey"
            columns: ["shift_id"]
            isOneToOne: false
            referencedRelation: "shifts"
            referencedColumns: ["id"]
          },
        ]
      }
      lead_activity: {
        Row: {
          actor_id: string
          content: string
          created_at: string
          id: string
          lead_id: string
          type: Database["public"]["Enums"]["lead_activity_type"]
        }
        Insert: {
          actor_id: string
          content?: string
          created_at?: string
          id?: string
          lead_id: string
          type: Database["public"]["Enums"]["lead_activity_type"]
        }
        Update: {
          actor_id?: string
          content?: string
          created_at?: string
          id?: string
          lead_id?: string
          type?: Database["public"]["Enums"]["lead_activity_type"]
        }
        Relationships: [
          {
            foreignKeyName: "lead_activity_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lead_activity_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
        ]
      }
      leads: {
        Row: {
          call_log_id: string | null
          contact_id: string
          created_at: string
          door_knock_id: string | null
          id: string
          rep_id: string
          source: Database["public"]["Enums"]["lead_source"]
          stage: Database["public"]["Enums"]["lead_stage"]
          updated_at: string
        }
        Insert: {
          call_log_id?: string | null
          contact_id: string
          created_at?: string
          door_knock_id?: string | null
          id?: string
          rep_id: string
          source: Database["public"]["Enums"]["lead_source"]
          stage?: Database["public"]["Enums"]["lead_stage"]
          updated_at?: string
        }
        Update: {
          call_log_id?: string | null
          contact_id?: string
          created_at?: string
          door_knock_id?: string | null
          id?: string
          rep_id?: string
          source?: Database["public"]["Enums"]["lead_source"]
          stage?: Database["public"]["Enums"]["lead_stage"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "leads_contact_id_fkey"
            columns: ["contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leads_door_knock_id_fkey"
            columns: ["door_knock_id"]
            isOneToOne: false
            referencedRelation: "door_knocks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leads_rep_id_fkey"
            columns: ["rep_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          active: boolean
          created_at: string
          id: string
          name: string
          phone: string | null
          role: Database["public"]["Enums"]["user_role"]
          start_date: string | null
          territory_id: string | null
          updated_at: string
        }
        Insert: {
          active?: boolean
          created_at?: string
          id: string
          name: string
          phone?: string | null
          role?: Database["public"]["Enums"]["user_role"]
          start_date?: string | null
          territory_id?: string | null
          updated_at?: string
        }
        Update: {
          active?: boolean
          created_at?: string
          id?: string
          name?: string
          phone?: string | null
          role?: Database["public"]["Enums"]["user_role"]
          start_date?: string | null
          territory_id?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      push_subscriptions: {
        Row: {
          auth: string
          created_at: string
          endpoint: string
          id: string
          p256dh: string
          rep_id: string
          updated_at: string
        }
        Insert: {
          auth: string
          created_at?: string
          endpoint: string
          id?: string
          p256dh: string
          rep_id: string
          updated_at?: string
        }
        Update: {
          auth?: string
          created_at?: string
          endpoint?: string
          id?: string
          p256dh?: string
          rep_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "push_subscriptions_rep_id_fkey"
            columns: ["rep_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      shifts: {
        Row: {
          ended_at: string | null
          id: string
          rep_id: string
          started_at: string
        }
        Insert: {
          ended_at?: string | null
          id?: string
          rep_id: string
          started_at?: string
        }
        Update: {
          ended_at?: string | null
          id?: string
          rep_id?: string
          started_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "shifts_rep_id_fkey"
            columns: ["rep_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      create_knock_with_contact: {
        Args: {
          p_address: string
          p_follow_up_at: string
          p_idempotency_key: string
          p_lat: number
          p_lng: number
          p_notes: string
          p_outcome: Database["public"]["Enums"]["door_outcome"]
          p_postcode: string
          p_suburb: string
        }
        Returns: {
          id: string
          knocked_at: string
          lat: number
          lead_created: boolean
          lead_id: string
          lng: number
          outcome: Database["public"]["Enums"]["door_outcome"]
          was_duplicate: boolean
        }[]
      }
      get_admin_daily_rep_summary: {
        Args: { p_from: string; p_to: string }
        Returns: {
          appointments_set: number
          calls: number
          doors: number
          leads_added: number
          rep_id: string
          rep_name: string
        }[]
      }
      get_admin_knocks_in_bbox: {
        Args: {
          p_east: number
          p_from?: string
          p_north: number
          p_outcomes?: Database["public"]["Enums"]["door_outcome"][]
          p_rep_ids?: string[]
          p_south: number
          p_to?: string
          p_west: number
        }
        Returns: {
          address: string
          id: string
          knocked_at: string
          lat: number
          lng: number
          outcome: Database["public"]["Enums"]["door_outcome"]
          postcode: string
          rep_id: string
          rep_name: string
          suburb: string
        }[]
      }
      get_admin_low_activity_reps: {
        Args: { p_window_minutes?: number }
        Returns: {
          idle_minutes: number
          last_activity_at: string
          rep_id: string
          rep_name: string
          shift_id: string
          shift_started_at: string
        }[]
      }
      get_knocks_in_bbox: {
        Args: {
          p_east: number
          p_north: number
          p_rep_id: string
          p_south: number
          p_west: number
        }
        Returns: {
          id: string
          knocked_at: string
          lat: number
          lng: number
          outcome: Database["public"]["Enums"]["door_outcome"]
        }[]
      }
      get_knocks_near_point: {
        Args: {
          p_lat: number
          p_limit?: number
          p_lng: number
          p_radius_m?: number
        }
        Returns: {
          id: string
          is_own: boolean
          knocked_at: string
          outcome: Database["public"]["Enums"]["door_outcome"]
          rep_id: string
          rep_name: string
        }[]
      }
      is_admin: { Args: never; Returns: boolean }
    }
    Enums: {
      call_outcome:
        | "answered_interested"
        | "answered_not_interested"
        | "voicemail"
        | "no_answer"
        | "wrong_number"
        | "callback_scheduled"
      door_outcome:
        | "interested"
        | "not_home"
        | "not_interested"
        | "do_not_knock"
        | "callback_requested"
        | "already_has_solar"
      lead_activity_type: "note" | "stage_change" | "call" | "knock"
      lead_source: "d2d" | "call"
      lead_stage:
        | "knocked_called"
        | "interested"
        | "appointment_set"
        | "pitched"
        | "proposal_sent"
        | "signed"
        | "lost"
      lost_reason: "price" | "not_interested" | "competitor" | "no_response"
      user_role: "admin" | "rep"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      call_outcome: [
        "answered_interested",
        "answered_not_interested",
        "voicemail",
        "no_answer",
        "wrong_number",
        "callback_scheduled",
      ],
      door_outcome: [
        "interested",
        "not_home",
        "not_interested",
        "do_not_knock",
        "callback_requested",
        "already_has_solar",
      ],
      lead_activity_type: ["note", "stage_change", "call", "knock"],
      lead_source: ["d2d", "call"],
      lead_stage: [
        "knocked_called",
        "interested",
        "appointment_set",
        "pitched",
        "proposal_sent",
        "signed",
        "lost",
      ],
      lost_reason: ["price", "not_interested", "competitor", "no_response"],
      user_role: ["admin", "rep"],
    },
  },
} as const

